# Spring Boot Configuration
spring:
  application:
    name: claude-automator

# Logging Configuration
logging:
  level:
    com.claude.automator: DEBUG
    io.github.jspinak.brobot: INFO

# Brobot Configuration (v1.1.0+)
brobot:
  core:
    image-path: images       # Base path for images
    mock: false
  startup:
    # New auto-verification system (v1.1.0+)
    auto-verify: true
    verify-states: "Working,Prompt"  # States to verify
    clear-states-before-verify: true
    ui-stabilization-delay: 2.0
    throw-on-failure: false
    run-diagnostics-on-failure: true
  sikuli:
    highlight: true