brobot:
  core:
    mock: true              # Use mock mode for demonstration
    image-path: images/     # Path to image resources
  screenshot:
    save-history: true      # Save action history to see highlights
    save-snapshots: false   # Don't save regular screenshots
    history-path: history/  # History directory
  mouse:
    move-delay: 0.5         # Mouse movement delay

logging:
  level:
    com.example.pureactions: DEBUG
    io.github.jspinak.brobot: INFO
    io.github.jspinak.brobot.action: DEBUG  # See action details