# Action Logging Configuration
spring:
  application:
    name: automatic-action-logging
  main:
    banner-mode: off

# Brobot Configuration
brobot:
  core:
    # Run in mock mode for examples
    mock: true
    # Enable verbose logging
    verbose: true

  # Action settings
  action:
    # Default timeouts
    max-wait: 5

  # Find settings
  find:
    similarity: 0.8

# Comprehensive Logging Configuration
logging:
  # Log levels by package
  level:
    root: INFO
    com.example.logging: DEBUG
    com.example.logging.examples: DEBUG
    com.example.logging.workflows: INFO
    io.github.jspinak.brobot: INFO
    # Show action execution details
    io.github.jspinak.brobot.action: DEBUG
    # Show find operation details
    io.github.jspinak.brobot.action.basic.find: DEBUG
    # Show state management
    io.github.jspinak.brobot.statemanagement: INFO

  # Console output pattern with MDC support
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{workflow}] [%X{step}] - %msg%n'

  # File output configuration
  file:
    name: logs/automation.log
    # Include MDC in file output
    pattern:
      file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{workflow}] [%X{step}] [%X{userId}] - %msg%n'

  # Rolling file configuration
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 100MB

# MDC (Mapped Diagnostic Context) fields
# These are available for use in logging patterns
mdc:
  fields:
    - workflow     # Current workflow name
    - step         # Current step in workflow
    - userId       # User identifier
    - sessionId    # Session identifier
    - taskId       # Task identifier
    - field        # Form field being processed
    - action       # Current action type
    - duration_ms  # Action duration
    - success      # Action success status

# Performance monitoring
performance:
  # Log slow actions
  slow-action-threshold-ms: 1000
  # Log action statistics every N actions
  stats-interval: 100
