export const ActionOptions = {
    FIND: 'FIND',
    CLICK: 'CLICK',
    DEFINE: 'DEFINE',
    TYPE: 'TYPE',
    MOVE: 'MOVE',
    VANISH: 'VANISH',
    HIGHLIGHT: 'HIGHLIGHT',
    SCROLL_MOUSE_WHEEL: 'SCROLL_MOUSE_WHEEL',
    MOUSE_DOWN: 'MOUSE_DOWN',
    MOUSE_UP: 'MOUSE_UP',
    KEY_DOWN: 'KEY_DOWN',
    KEY_UP: 'KEY_UP',
    CLASSIFY: 'CLASSIFY',
    CLICK_UNTIL: 'CLICK_UNTIL',
    DRAG: 'DRAG'
};