# ConditionalActionChain Examples Configuration
spring:
  application:
    name: conditional-chains-examples
  main:
    banner-mode: off

# Brobot Configuration
brobot:
  core:
    # Run in mock mode for examples
    mock: true
    # Show detailed action logs
    verbose: true
    
  # Success criteria for actions
  action:
    # How long to wait for elements to appear
    max-wait: 5
    
  # Image recognition settings
  find:
    similarity: 0.8
    
# Logging configuration
logging:
  level:
    root: INFO
    com.example.conditionalchains: DEBUG
    io.github.jspinak.brobot: INFO
    # Show detailed conditional chain execution
    io.github.jspinak.brobot.action: DEBUG
    io.github.jspinak.brobot.util.ConditionalActionWrapper: DEBUG
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'