spring:
  application:
    name: brobot-runner

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:file:./data/brobot-runner;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

# Brobot Runner Configuration
brobot:
  # Persistence Module Configuration
  persistence:
    enabled: true
    type: DATABASE                        # Use database persistence (FILE, DATABASE, MEMORY)
    performance:
      async-recording: true
      buffer-size: 100
      flush-interval-seconds: 60
    database:
      batch-size: 100

  runner:
    # Action Recording Configuration (now delegated to persistence module)
    recording:
      enabled: false                      # Recording disabled by default
      auto-save-interval: 60              # Auto-save every 60 seconds
      buffer-size: 100                    # Buffer 100 records before flush
      max-records-per-session: 10000      # Max 10k records per session
      max-sessions: 100                   # Keep max 100 sessions
      export-format: JSON                 # Default export format
      compress-exports: false             # Don't compress by default
      store-screenshots: false            # Don't store screenshots by default
      max-screenshot-size: 500            # Max 500KB per screenshot

      # Database settings
      database:
        batch-size: 100                  # Batch insert size
        async-recording: true             # Use async recording
        pool-size: 5                      # Connection pool size

      # Performance settings
      performance:
        max-memory-buffer: 50             # 50MB memory buffer
        flush-on-memory-pressure: true   # Auto-flush on memory pressure
        thread-pool-size: 3               # 3 threads for async ops
        queue-capacity: 1000              # Queue up to 1000 operations

      # Cleanup settings
      cleanup:
        retention-days: 30                # Keep sessions for 30 days
        enabled: true                     # Enable auto-cleanup
        schedule: "0 0 2 * * ?"          # Run at 2 AM daily
        auto-archive: false               # Don't auto-archive by default
        archive-path: ./archive          # Archive directory

# Logging Configuration
logging:
  level:
    io.github.jspinak.brobot.runner: INFO
    io.github.jspinak.brobot.runner.service: DEBUG
    io.github.jspinak.brobot.runner.persistence: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN

  file:
    name: logs/brobot-runner.log

  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
