version: '3'
services:
  brobot-app:
    image: brobot-image:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://reports_v6pz_user:qNlVLvRuYKhhZlrWWPAwUHt2vWuNDZfM@dpg-cjromglv2qks73aab7o0-a/reports_v6pz
