spring:
  application:
    name: unit-testing-example

# Brobot configuration
brobot:
  mock:
    enabled: true
    verbose: false

  action:
    max-wait: 5
    delay-between-actions: 100

  logging:
    level: INFO

# Logging configuration
logging:
  level:
    root: INFO
    com.example.unittesting: DEBUG
    io.github.jspinak.brobot: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
