brobot:
  core:
    mock: true              # Use mock mode for demonstration
    image-path: images/     # Path to image resources
  screenshot:
    save-history: true      # Save illustrated screenshots
    save-snapshots: false
    path: screenshots/
    history-path: history/  # See color analysis visualizations here
  illustration:
    draw-find: true
    draw-classify: true     # Important for color visualization
  analysis:
    k-means-in-profile: 5   # Number of k-means colors to analyze
    max-k-means-to-store: 10

logging:
  level:
    com.example.usingcolor: DEBUG
    io.github.jspinak.brobot: INFO
    io.github.jspinak.brobot.action.color: DEBUG  # See color analysis details
