brobot:
  core:
    mock: true              # Use mock mode for demonstration
    image-path: images/     # Path to image resources
  screenshot:
    save-history: true      # Important to visualize nested/confirmed finds
    save-snapshots: false
    history-path: history/
  illustration:
    draw-find: true
    draw-repeated-actions: true  # Shows chain progression
  mouse:
    move-delay: 0.5

logging:
  level:
    com.example.combiningfinds: DEBUG
    io.github.jspinak.brobot: INFO
    io.github.jspinak.brobot.action.chain: DEBUG  # See chaining details
