# Movement Examples Configuration
spring:
  application:
    name: movement-examples
  main:
    banner-mode: off

# Brobot Configuration
brobot:
  core:
    # Run in mock mode for examples
    mock: true
    # Enable verbose logging
    verbose: true

  # Action settings
  action:
    # Default timeouts
    max-wait: 5

  # Find settings
  find:
    similarity: 0.8

  # Movement settings
  movement:
    # Default movement time (seconds)
    default-move-time: 0.5
    # Default movement pattern
    default-pattern: SMOOTH

  # Drag settings
  drag:
    # Default hold time before drag
    default-hold-time: 0.5
    # Default drag speed
    default-speed: NORMAL

  # Scroll settings
  scroll:
    # Default scroll clicks
    default-clicks: 3
    # Default pause between scrolls
    default-pause: 0.1

# Mouse movement configuration
mouse:
  # Movement patterns available:
  # - SMOOTH: Natural curved movement
  # - LINEAR: Direct line movement
  # - SIGMOID: S-curve movement
  # - RANDOM: Random variations
  movement:
    patterns:
      - SMOOTH
      - LINEAR
      - SIGMOID
      - RANDOM

  # Speed presets
  speed:
    slow: 2.0
    normal: 1.0
    fast: 0.3

# Logging configuration
logging:
  level:
    root: INFO
    com.example.movement: DEBUG
    io.github.jspinak.brobot: INFO
    # Show movement details
    io.github.jspinak.brobot.action.basic.move: DEBUG
    io.github.jspinak.brobot.action.composite.drag: DEBUG
    io.github.jspinak.brobot.action.basic.scroll: DEBUG
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
