spring:
  application:
    name: form-automation-example

# Brobot configuration
brobot:
  # Logging configuration
  logging:
    # Console output level
    console-level: NORMAL  # QUIET, NORMAL, or VERBOSE
    
    # Enable visual feedback
    visual-feedback: true
    
    # Highlight matches
    highlight-matches: true
    highlight-duration: 2.0
    
  # Action timing
  actions:
    # Default pause between actions
    default-pause: 0.5
    
    # Typing speed
    type-delay: 0.05
    
    # Wait after clicks
    click-pause: 0.3
    
  # Find configuration
  find:
    # Default similarity threshold
    similarity: 0.85
    
    # Search timeout
    timeout: 5.0

# Application-specific settings
form-automation:
  # Maximum retries for form submission
  max-retries: 3
  
  # Wait time between retries (seconds)
  retry-delay: 2.0
  
  # Form load timeout (seconds)
  form-load-timeout: 10
  
  # Validation check delay
  validation-delay: 1.0

# Logging configuration
logging:
  level:
    com.example.form: DEBUG
    io.github.jspinak.brobot: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"