spring:
  application:
    name: state-transitions-example

# Brobot configuration for state management
brobot:
  # State management settings
  states:
    # Maximum time to wait for state transitions (seconds)
    transition-timeout: 30
    
    # Time to wait between state checks
    check-interval: 0.5
    
    # Number of state indicators required for confirmation
    min-indicators: 2
    
  # Logging configuration
  logging:
    # Console output level
    console-level: NORMAL
    
    # Log state transitions
    log-transitions: true
    
    # Log state verifications
    log-verifications: true
    
  # Action timing
  actions:
    # Default pause between actions
    default-pause: 0.5
    
    # Wait after state transitions
    transition-pause: 1.0
    
  # Find configuration for state detection
  find:
    # Similarity threshold for state indicators
    similarity: 0.85
    
    # Quick search for state verification
    quick-search: true

# Application-specific settings
state-navigation:
  # Maximum retries for failed transitions
  max-transition-retries: 3
  
  # Delay between transition retries
  retry-delay: 2.0
  
  # Enable alternate navigation paths
  use-alternate-paths: true
  
  # State verification mode
  verification-mode: COMPREHENSIVE  # QUICK, NORMAL, COMPREHENSIVE

# Logging configuration
logging:
  level:
    com.example.states: DEBUG
    io.github.jspinak.brobot: INFO
    io.github.jspinak.brobot.navigation: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{20} - %msg%n"