name: Build Verification

on:
  push:
    branches: [ main, develop, 'feature/**' ]
  pull_request:
    branches: [ main, develop ]

env:
  JAVA_VERSION: '21'
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  build:
    name: Verify Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      if: runner.os != 'Windows'

    - name: Build all modules
      shell: bash
      run: |
        echo "Building on ${{ matrix.os }}..."
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          ./gradlew.bat build -x test --no-daemon --stacktrace
        else
          ./gradlew build -x test --no-daemon --stacktrace
        fi
        echo "✅ Build successful on ${{ matrix.os }}"

    - name: Verify artifacts created
      shell: bash
      run: |
        echo "Checking build artifacts..."
        if ls library/build/libs/library-*.jar 1> /dev/null 2>&1; then
          echo "✅ Library JAR created"
          ls -la library/build/libs/library-*.jar
        else
          echo "❌ Library JAR not found"
          echo "Contents of library/build/libs (if exists):"
          ls -la library/build/libs/ 2>/dev/null || echo "Directory doesn't exist"
          exit 1
        fi
