name: Deploy JavaDocs

on:
  push:
    tags:
      - 'v*' # Deploy on version tags
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Generate JavaDocs
        run: |
          ./gradlew :library:javadocForGitHubPages
          ./gradlew :library:createLatestSymlink

      - name: Prepare JavaDocs for deployment
        run: |
          mkdir -p _site/api

          # Copy only the versioned directories and symlinks, not the root files
          # This ensures the package structure is preserved
          if [ -d library/build/docs/javadoc/1.1.0 ]; then
            cp -r library/build/docs/javadoc/1.1.0 _site/api/
          fi
          if [ -L library/build/docs/javadoc/latest ] || [ -d library/build/docs/javadoc/latest ]; then
            cp -r library/build/docs/javadoc/latest _site/api/
          fi

          # Create an index.html at the root that redirects to the latest version
          cat > _site/api/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="UTF-8">
              <meta http-equiv="refresh" content="0; url=latest/index.html">
              <title>Brobot API Documentation</title>
          </head>
          <body>
              <p>Redirecting to <a href="latest/index.html">latest API documentation</a>...</p>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-javadoc
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
