name: Brobot CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Temporarily move module-info.java files out of the way
      - name: Disable module-info files
        run: |
          find . -name "module-info.java" -type f -exec mv {} {}.disabled \;
          echo "Module info files have been disabled"

      # Create a test environment setup specifically for GitHub Actions
      - name: Setup test environment
        run: |
          # Set up directories for tests
          mkdir -p /home/runner/work/brobot/brobot/screenshots
          mkdir -p /home/runner/work/brobot/brobot/images
          mkdir -p /home/runner/work/brobot/brobot/history

          # Copy image files to screenshots directory for mock tests
          find /home/runner/work/brobot/brobot -type f -name "*.png" -exec cp {} /home/runner/work/brobot/brobot/screenshots/ \; 2>/dev/null || true
          find /home/runner/work/brobot/brobot -type f -name "*.jpg" -exec cp {} /home/runner/work/brobot/brobot/screenshots/ \; 2>/dev/null || true

          # Ensure permissions are correct
          chmod -R 755 /home/runner/work/brobot/brobot/screenshots

          # Set up xvfb for headless GUI tests
          sudo apt-get update
          sudo apt-get install -y xvfb

      # Build with non-modular approach
      - name: Build with Gradle (excluding library-features)
        run: |
          ./gradlew :library:build -x test \
            -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=1g"
        env:
          SPRING_PROFILES_ACTIVE: "ci"
          _JAVA_OPTIONS: "-Djava.awt.headless=true"

      - name: Run tests with Python script
        run: |
          python3 library/scripts/run-all-tests.py library --mode sequential --timeout 60 --retry-failed
        env:
          # Activate CI profile
          SPRING_PROFILES_ACTIVE: "ci"
          BROBOT_SCREENSHOTS_PATH: "/home/runner/work/brobot/brobot/screenshots"
          _JAVA_OPTIONS: "-Djava.awt.headless=true -Dio.github.jspinak.brobot.actions.BrobotSettings.screenshotPath=/home/runner/work/brobot/brobot/screenshots/ -Dio.github.jspinak.brobot.actions.BrobotSettings.screenshotFilename=screen"

      - name: Upload test results
        if: always() && (success() || failure())
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/build/test-results/test"
          if-no-files-found: warn

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

  # Runner packaging job removed - runner module no longer in project
